// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.API.Data;

#nullable disable

namespace WebApp.Api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApp.API.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 3, 23, 14, 27, 54, 829, DateTimeKind.Local).AddTicks(5848),
                            Email = "paul.taylor6@yahoo.com",
                            FirstName = "Paul",
                            LastName = "Taylor"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 3, 23, 14, 27, 54, 829, DateTimeKind.Local).AddTicks(5862),
                            Email = "peter.jones35@outlook.com",
                            FirstName = "Peter",
                            LastName = "Jones"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2024, 3, 23, 14, 27, 54, 829, DateTimeKind.Local).AddTicks(5864),
                            Email = "david.jones72@gmail.com",
                            FirstName = "David",
                            LastName = "Jones"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2024, 3, 23, 14, 27, 54, 829, DateTimeKind.Local).AddTicks(5866),
                            Email = "steven.brown12@outlook.com",
                            FirstName = "Steven",
                            LastName = "Brown"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2024, 3, 23, 14, 27, 54, 829, DateTimeKind.Local).AddTicks(5873),
                            Email = "steven.miller95@outlook.com",
                            FirstName = "Steven",
                            LastName = "Miller"
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2024, 3, 23, 14, 27, 54, 829, DateTimeKind.Local).AddTicks(5876),
                            Email = "andrew.smith39@yahoo.com",
                            FirstName = "Andrew",
                            LastName = "Smith"
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2024, 3, 23, 14, 27, 54, 829, DateTimeKind.Local).AddTicks(5878),
                            Email = "steven.taylor86@outlook.com",
                            FirstName = "Steven",
                            LastName = "Taylor"
                        },
                        new
                        {
                            UserId = 8,
                            CreatedAt = new DateTime(2024, 3, 23, 14, 27, 54, 829, DateTimeKind.Local).AddTicks(5880),
                            Email = "paul.garcia84@gmail.com",
                            FirstName = "Paul",
                            LastName = "Garcia"
                        },
                        new
                        {
                            UserId = 9,
                            CreatedAt = new DateTime(2024, 3, 23, 14, 27, 54, 829, DateTimeKind.Local).AddTicks(5881),
                            Email = "paul.garcia2@yahoo.com",
                            FirstName = "Paul",
                            LastName = "Garcia"
                        },
                        new
                        {
                            UserId = 10,
                            CreatedAt = new DateTime(2024, 3, 23, 14, 27, 54, 829, DateTimeKind.Local).AddTicks(5884),
                            Email = "andrew.jones53@gmail.com",
                            FirstName = "Andrew",
                            LastName = "Jones"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
